---
name: Catalog (Update Belug-Apps chart)
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      ref:
        description: "`belug-apps/belug-apps` ref to synchronize with"
        required: true
        default: main
        type: string
      train:
        description: which catalog trains should be synchronized
        required: true
        type: environment
  workflow_call:
    inputs:
      ref:
        description: "`belug-apps/belug-apps` ref to synchronize with"
        required: true
        type: string
      train:
        description: which catalog trains should be synchronized
        required: true
        type: string

jobs:
  sync_catalog:
    runs-on: ubuntu-latest
    environment: ${{ inputs.train }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # tag=1.7.0
        id: app_auth
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PKEY }}

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          ref: main
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: belug-apps/belug-apps
          ref: ${{ inputs.ref }}
          path: vendors/belug-apps

      - name: Find latest Belug-Apps version
        id: helm
        run: echo >> "$GITHUB_OUTPUT" "version=$(grep '^version:' vendors/belug-apps/charts/belug-apps/Chart.yaml | awk '{print $2}')"

      - name: Sync latest Belug-Apps version (${{ steps.helm.outputs.version }})
        run: |
          mkdir --parent ${{ inputs.train }}/belug-apps
          rsync --archive --recursive --delete --verbose vendors/belug-apps/charts/belug-apps/ ${{ inputs.train }}/belug-apps/${{ steps.helm.outputs.version }}
          rm --recursive vendors/

      - uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5 # v5.0.0
        id: create-pr
        with:
          commit-message: sync Belug-Apps chart with ${{ inputs.train }} (${{ steps.helm.outputs.version }})
          author: belug-apps[bot] <116495032+belug-apps[bot]@users.noreply.github.com>
          committer: belug-apps[bot] <116495032+belug-apps[bot]@users.noreply.github.com>
          base: main
          body: ''
          branch: catalog/sync-${{ inputs.train }}-${{ inputs.ref }}
          delete-branch: true
          signoff: true
          title: Sync catalog (${{ inputs.train }}) with Belug-Apps chart (${{ steps.helm.outputs.version }})

      - uses: peter-evans/enable-pull-request-automerge@60812ab1c2c6c6a8932b4d6e059becafaf386256 # v2.3.0
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        with:
          merge-method: squash
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          token: ${{ steps.app_auth.outputs.token }}
      - uses: hmarr/auto-approve-action@de8ae18c173c131e182d4adf2c874d8d2308a85b # tag=v3.1.0
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        with:
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          github-token: ${{ steps.app_auth.outputs.token }}
